### ISSUE TITLE
Unpickling error

### ISSUE THREAD

**Issue by yusuf-khaled** [openai/gym-wikinav#1]
Full error:

Traceback (most recent call last):
  File "PATH\running-tests/running-env.py", line 4, in <module>
    env = gym.make('wikinav-v12')
  File "PATHAnaconda3\lib\site-packages\gym\envs\registration.py", line 167, in make
    return registry.make(id)
  File "PATH\Anaconda3\lib\site-packages\gym\envs\registration.py", line 119, in make
    env = spec.make()
  File "PATH\Anaconda3\lib\site-packages\gym\envs\registration.py", line 86, in make
    env = cls(**self._kwargs)
  File "PATH\envs\wikinav_env\environment.py", line 108, in __init__
    super(EmbeddingWikiNavEnv, self).__init__(*args, **kwargs)
  File "PATH\envs\wikinav_env\environment.py", line 25, in __init__
    graph = web_graph.EmbeddedWikispeediaGraph.get_default_graph()
  File "PATH\envs\wikinav_env\web_graph.py", line 190, in get_default_graph
    graph = cls(graph_path, path_length, emb_paths=[emb_path])
  File "PATH\envs\wikinav_env\web_graph.py", line 99, in __init__
    data = pickle.load(data_f)
_pickle.UnpicklingError: invalid load key, 'v'.

Essentially the line 
        with open(data_path, "rb") as data_f:
            data = pickle.load(data_f)
in web_graph.py raises this unpickling error.

Any ideas? Would really appreciate any feedback so I can get this great project running on my machine.

**Comment by yhbk12** [comment]
Yes I've just encountered that issue too!

Would love a solution here.
